create table if not exists public."__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table public."__EFMigrationsHistory"
    owner to postgres;

create table if not exists public."AspNetRoles"
(
    "Id"               bigint generated by default as identity
        constraint "PK_AspNetRoles"
            primary key,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

alter table public."AspNetRoles"
    owner to postgres;

create unique index if not exists "RoleNameIndex"
    on public."AspNetRoles" ("NormalizedName");

create table if not exists public."County"
(
    "Id"   bigint generated by default as identity
        constraint "PK_County"
            primary key,
    "Name" text not null
);

alter table public."County"
    owner to postgres;

create table if not exists public."Illness"
(
    "Id"          bigint generated by default as identity
        constraint "PK_Illness"
            primary key,
    "Description" text not null,
    "Name"        text not null
);

alter table public."Illness"
    owner to postgres;

create table if not exists public."RiskFactor"
(
    "Id"          bigint generated by default as identity
        constraint "PK_RiskFactor"
            primary key,
    "Description" text not null,
    "Name"        text not null
);

alter table public."RiskFactor"
    owner to postgres;

create table if not exists public."Speciality"
(
    "Id"   bigint generated by default as identity
        constraint "PK_Speciality"
            primary key,
    "Name" text not null
);

alter table public."Speciality"
    owner to postgres;

create table if not exists public."AspNetRoleClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetRoleClaims"
            primary key,
    "RoleId"     bigint not null
        constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            references public."AspNetRoles"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table public."AspNetRoleClaims"
    owner to postgres;

create index if not exists "IX_AspNetRoleClaims_RoleId"
    on public."AspNetRoleClaims" ("RoleId");

create table if not exists public."Region"
(
    "Id"       bigint generated by default as identity
        constraint "PK_Region"
            primary key,
    "CountyId" bigint not null
        constraint "FK_Region_County_CountyId"
            references public."County"
            on delete cascade,
    "Name"     text   not null
);

alter table public."Region"
    owner to postgres;

create index if not exists "IX_Region_CountyId"
    on public."Region" ("CountyId");

create table if not exists public."City"
(
    "Id"       bigint generated by default as identity
        constraint "PK_City"
            primary key,
    "RegionId" bigint not null
        constraint "FK_City_Region_RegionId"
            references public."Region"
            on delete cascade,
    "Name"     text   not null
);

alter table public."City"
    owner to postgres;

create index if not exists "IX_City_RegionId"
    on public."City" ("RegionId");

create table if not exists public."Hospital"
(
    "Id"          bigint generated by default as identity
        constraint "PK_Hospital"
            primary key,
    "Description" text     not null,
    "Address"     text     not null,
    "StartedTime" time     not null,
    "EndTime"     time     not null,
    "Contacts"    text     not null,
    "Rating"      smallint not null,
    "Email"       text     not null,
    "CityId"      bigint   not null
        constraint "FK_Hospital_City_CityId"
            references public."City"
            on delete cascade,
    "Name"        text     not null
);

alter table public."Hospital"
    owner to postgres;

create index if not exists "IX_Hospital_CityId"
    on public."Hospital" ("CityId");

create table if not exists public."AspNetUsers"
(
    "Id"                     bigint generated by default as identity
        constraint "PK_AspNetUsers"
            primary key,
    "Name"                   text                     not null,
    "Surname"                text                     not null,
    "Patronymic"             text,
    "RefreshToken"           text,
    "RefreshTokenExpiryTime" timestamp with time zone not null,
    "Discriminator"          text                     not null,
    "SpecialityId"           bigint
        constraint "FK_AspNetUsers_Speciality_SpecialityId"
            references public."Speciality"
            on delete cascade,
    "Doctor_HospitalId"      bigint
        constraint "FK_AspNetUsers_Hospital_Doctor_HospitalId"
            references public."Hospital",
    "RiskFactorId"           bigint
        constraint "FK_AspNetUsers_RiskFactor_RiskFactorId"
            references public."RiskFactor"
            on delete cascade,
    "IllnessId"              bigint
        constraint "FK_AspNetUsers_Illness_IllnessId"
            references public."Illness"
            on delete cascade,
    "HospitalId"             bigint
        constraint "FK_AspNetUsers_Hospital_HospitalId"
            references public."Hospital",
    "UserName"               varchar(256),
    "NormalizedUserName"     varchar(256),
    "Email"                  varchar(256),
    "NormalizedEmail"        varchar(256),
    "EmailConfirmed"         boolean                  not null,
    "PasswordHash"           text,
    "SecurityStamp"          text,
    "ConcurrencyStamp"       text,
    "PhoneNumber"            text,
    "PhoneNumberConfirmed"   boolean                  not null,
    "TwoFactorEnabled"       boolean                  not null,
    "LockoutEnd"             timestamp with time zone,
    "LockoutEnabled"         boolean                  not null,
    "AccessFailedCount"      integer                  not null
);

alter table public."AspNetUsers"
    owner to postgres;

create index if not exists "EmailIndex"
    on public."AspNetUsers" ("NormalizedEmail");

create index if not exists "IX_AspNetUsers_Doctor_HospitalId"
    on public."AspNetUsers" ("Doctor_HospitalId");

create index if not exists "IX_AspNetUsers_HospitalId"
    on public."AspNetUsers" ("HospitalId");

create index if not exists "IX_AspNetUsers_IllnessId"
    on public."AspNetUsers" ("IllnessId");

create index if not exists "IX_AspNetUsers_RiskFactorId"
    on public."AspNetUsers" ("RiskFactorId");

create index if not exists "IX_AspNetUsers_SpecialityId"
    on public."AspNetUsers" ("SpecialityId");

create unique index if not exists "UserNameIndex"
    on public."AspNetUsers" ("NormalizedUserName");

create table if not exists public."AspNetUserClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetUserClaims"
            primary key,
    "UserId"     bigint not null
        constraint "FK_AspNetUserClaims_AspNetUsers_UserId"
            references public."AspNetUsers"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table public."AspNetUserClaims"
    owner to postgres;

create index if not exists "IX_AspNetUserClaims_UserId"
    on public."AspNetUserClaims" ("UserId");

create table if not exists public."AspNetUserLogins"
(
    "LoginProvider"       text   not null,
    "ProviderKey"         text   not null,
    "ProviderDisplayName" text,
    "UserId"              bigint not null
        constraint "FK_AspNetUserLogins_AspNetUsers_UserId"
            references public."AspNetUsers"
            on delete cascade,
    constraint "PK_AspNetUserLogins"
        primary key ("LoginProvider", "ProviderKey")
);

alter table public."AspNetUserLogins"
    owner to postgres;

create index if not exists "IX_AspNetUserLogins_UserId"
    on public."AspNetUserLogins" ("UserId");

create table if not exists public."AspNetUserRoles"
(
    "UserId" bigint not null
        constraint "FK_AspNetUserRoles_AspNetUsers_UserId"
            references public."AspNetUsers"
            on delete cascade,
    "RoleId" bigint not null
        constraint "FK_AspNetUserRoles_AspNetRoles_RoleId"
            references public."AspNetRoles"
            on delete cascade,
    constraint "PK_AspNetUserRoles"
        primary key ("UserId", "RoleId")
);

alter table public."AspNetUserRoles"
    owner to postgres;

create index if not exists "IX_AspNetUserRoles_RoleId"
    on public."AspNetUserRoles" ("RoleId");

create table if not exists public."AspNetUserTokens"
(
    "UserId"        bigint not null
        constraint "FK_AspNetUserTokens_AspNetUsers_UserId"
            references public."AspNetUsers"
            on delete cascade,
    "LoginProvider" text   not null,
    "Name"          text   not null,
    "Value"         text,
    constraint "PK_AspNetUserTokens"
        primary key ("UserId", "LoginProvider", "Name")
);

alter table public."AspNetUserTokens"
    owner to postgres;

INSERT INTO public."County"(
	"Name")
	VALUES ('Дальневосточный'),
		   ('Приволжский'),
		   ('Северо-Западный'),
		   ('Северо-Кавказский'),
		   ('Сибирский'),
		   ('Уральский'),
		   ('Центральный'),
		   ('Южный');

INSERT INTO public."Region"(
	"CountyId", "Name")
	VALUES (1, 'Амурская область'),
	       (1, 'Республика Бурятия'),
	       (1, 'Еврейская автономная область'),
	       (1, 'Забайкальский край'),
	       (1, 'Камчатский край'),
	       (1, 'Магаданская область'),
	       (1, 'Приморский край'),
	       (1, 'Республика Саха (Якутия)'),
	       (1, 'Сахалинская область'),
	       (1, 'Хабаровский край'),
	       (1, 'Чукотский автономный округ'),
	       (2, 'Республика Башкортостан'),
	       (2, 'Кировская область'),
	       (2, 'Республика Марий Эл'),
	       (2, 'Республика Мордовия'),
	       (2, 'Нижегородская область'),
	       (2, 'Оренбургская область'),
	       (2, 'Пензенская область'),
	       (2, 'Пермский край'),
	       (2, 'Самарская область'),
	       (2, 'Саратовская область'),
	       (2, 'Республика Татарстан'),
	       (2, 'Удмуртская Республика'),
	       (2, 'Ульяновская область'),
	       (2, 'Чувашская Республика'),
	       (3, 'Архангельская область'),
	       (3, 'Вологодская область'),
	       (3, 'Калининградская область'),
	       (3, 'Республика Карелия'),
	       (3, 'Республика Коми'),
	       (3, 'Ленинградская область'),
	       (3, 'Мурманская область'),
	       (3, 'Ненецкий автономный округ'),
	       (3, 'Новгородская область'),
	       (3, 'Псковская область'),
	       (3, 'Санкт-Петербург'),
	       (4, 'Республика Дагестан'),
	       (4, 'Республика Ингушетия'),
	       (4, 'Кабардино-Балкарская Республика'),
	       (4, 'Карачаево-Черкесская Республика'),
	       (4, 'Республика Северная Осетия — Алания'),
	       (4, 'Ставропольский край'),
	       (4, 'Чеченская Республика'),
	       (5, 'Республика Алтай'),
		   (5, 'Алтайский край'),
		   (5, 'Иркутская область'),
		   (5, 'Кемеровская область — Кузбасс'),
		   (5, 'Красноярский край'),
		   (5, 'Новосибирская область'),
		   (5, 'Омская область'),
		   (5, 'Томская область'),
		   (5, 'Республика Тыва'),
		   (5, 'Республика Хакасия'),
		   (6, 'Курганская область'),
		   (6, 'Свердловская область'),
		   (6, 'Тюменская область'),
		   (6, 'Ханты-Манскийский автономный округ-Югра'),
		   (6, 'Челябинская область'),
		   (6, 'Ямало-Немецкий автономный округ'),
		   (7, 'Белгородская область'),
		   (7, 'Брянская область'),
		   (7, 'Владимирская область'),
		   (7, 'Воронежская область'),
		   (7, 'Ивановская область'),
		   (7, 'Калужская область'),
		   (7, 'Костромская область'),
		   (7, 'Курская область'),
		   (7, 'Липецкая область'),
		   (7, 'Москва'),
		   (7, 'Московская область'),
		   (7, 'Орловская область'),
		   (7, 'Рязанская область'),
		   (7, 'Смоленская область'),
		   (7, 'Тамбовская область'),
		   (7, 'Тверская область'),
		   (7, 'Тульская область'),
		   (7, 'Ярославская область'),
		   (8, 'Республика Адыгея'),
		   (8, 'Астраханская область'),
		   (8, 'Волгоградская область'),
		   (8, 'Республика Калмыкия'),
		   (8, 'Краснодарский край'),
		   (8, 'Ростовская область'),
		   (8, 'Республика Крым'),
		   (8, 'Севастополь');

INSERT INTO public."City"(
	"RegionId", "Name")
	VALUES (66, 'Буй'),
	       (66, 'Волгореченск'),
	       (66, 'Галич'),
	       (66, 'Кологрив'),
	       (66, 'Кострома'),
	       (66, 'Макарьев'),
	       (66, 'Мантурово'),
	       (66, 'Нерехта'),
	       (66, 'Нея'),
	       (66, 'Солигалич'),
	       (66, 'Чухлома'),
	       (66, 'Шарья'),
               (1, 'Белогорск'),
	       (1, 'Благовещенск'),
	       (1, 'Завитинск'),
	       (1, 'Зея'),
	       (1, 'Райчихинск'),
	       (1, 'Свободный'),
	       (1, 'Сковородино'),
	       (1, 'Тында'),
	       (1, 'Циолковский'),
	       (1, 'Шимановск');;

INSERT INTO public."Hospital"(
	"Description", "Address", "StartedTime", "EndTime", "Contacts", "Rating", "Email", "CityId", "Name")
	VALUES ('Описание', 'улица Пушкина, дом колатушкина 3', '06:00:00', '23:00:00', 'регистратура - 1111111111', '5', 'pergor@mail.ru', 5, 'первая городская больница');

INSERT INTO public."AspNetRoles"(
	"Name", "NormalizedName")
	VALUES ('Patient', 'PATIENT'),
	       ('Doctor','DOCTOR'),
               ('Admin','ADMIN');