version: '3.4'

services:
  medicineproject.api:
    image: yantar/medicine-project-api
    build:
      context: .
      dockerfile: MedicineProject/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  postgres:
    container_name: "webMobileDb"
    image: postgres:15.3
    environment:
      POSTGRES_DB: MedicineProjectDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 301600
      PGDAT A: /data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    volumes:
    - .:/docker-entrypoint-initdb.d
    networks:
      - postgres

  postgres1:
    container_name: "desktopDB"
    image: postgres:15.3
    environment:
      POSTGRES_DB: MedicineProjectDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 301600
      PGDATA: /data/pgdata
    ports:
      - "2345:2345"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    #volumes:
    #- .:/docker-entrypoint-initdb.d
    networks:
      - postgres

  pgadmin:
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8000:80"
   networks:
     - postgres

networks:
  postgres:
    driver: bridge